Fixed logic around multiple running proxies

diff --git a/testdir/Makefile b/testdir/Makefile
--- a/testdir/Makefile
+++ b/testdir/Makefile
@@ -1,7 +1,7 @@
 # Makefile for testing the client/server C++ SDK instrumentation logic.
 #
 
-.PHONY: all check_pids check_proxy_pid check_server_pid check_client_pid check_links check_server_link check_client_link clean_links clean clean_server_link clean_client_link links server_links client_links start proxy_start server_start client_start stop proxy_stop server_stop client_stop status title_status proxy_status server_status client_status
+.PHONY: all check_pids proxy_check_pid server_check_pid client_check_pid check_links check_server_link check_client_link clean_links clean clean_server_link clean_client_link links server_links client_links start proxy_start server_start client_start stop proxy_stop server_stop client_stop status title_status proxy_status server_status client_status
 
 all: links
 	@echo "make all completed."
@@ -18,44 +18,49 @@ client_link: check_client_link
 clean: clean_server_link clean_client_link
 	@echo "Completed clean."
 
-clean_server_link: check_server_link check_server_pid
+clean_server_link: check_server_link server_check_pid
 	@if [ -h ${SERVER_EXE_NAME} ]; then\
 		echo "rm -f ${SERVER_EXE_NAME}";\
 		rm -f ${SERVER_EXE_NAME};\
 	fi;
 
-clean_client_link: check_client_link check_client_pid
+clean_client_link: check_client_link client_check_pid
 	@if [ -h ${CLIENT_EXE_NAME} ]; then\
 		echo "rm -f ${CLIENT_EXE_NAME}";\
 		rm -f ${CLIENT_EXE_NAME};\
 	fi;
 
-start: proxy_start server_start client_start
+start: server_start client_start
 	@echo "Completed program start for server & client."
 
-proxy_start: check_proxy_pid
+proxy_start: proxy_check_pid
 	@echo
+	@echo "About to start \"${PROXY_EXE_NAME}\"..."
 	@echo "Starting \"${PROXY_EXE_NAME}\" on `date` " > ${PROXY_LOG}
 	@${PROXY_EXE} >> ${PROXY_LOG} 2>&1 &
+	@sleep 2
 	@ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}" | awk ' { print $$2 } ' | head -1 > ${PROXY_PID_FILE}
 	@echo "Proxy started with pid: ${BOLD_YELLOW}`cat ${PROXY_PID_FILE}`${RESET_TERM}"
 	@echo "Sending output to: ${PROXY_LOG}"
 	@echo "Use this command to tail the output: ${BOLD_GREEN} tail -100f ${PROXY_LOG}${RESET_TERM}"
 	@echo
 
-server_start: check_server_link check_server_pid
+server_start: check_server_link server_check_pid
 	@echo
+	@echo "About to start \"${SERVER_EXE_NAME}\" using host \"${HOST}\", port \"${PORT}\", and HTTP root directory \"${HTTP_DIR}\"..."
 	@echo "Starting ${SERVER_EXE_NAME} using host ${HOST}, port ${PORT}, and HTTP root directory \"${HTTP_DIR}\"" > ${SERVER_LOG}
 	@echo "Executed on "`date` >> ${SERVER_LOG}
 	@${SDK_LOAD_PATH} ./${SERVER_EXE_NAME} ${HOST} ${PORT} ${HTTP_DIR} >> ${SERVER_LOG} 2>&1 &
+	@sleep 1
 	@ps -ef | grep -v grep | grep "${SERVER_EXE_NAME}" | grep "${HOST}" | grep "${PORT}" | awk ' { print $$2 } ' | head -1 > ${SERVER_PID_FILE}
 	@echo "Server started with pid: ${BOLD_YELLOW}`cat ${SERVER_PID_FILE}`${RESET_TERM}"
 	@echo "Sending output to: ${SERVER_LOG}"
 	@echo "Use this command to tail the output: ${BOLD_GREEN} tail -100f ${SERVER_LOG}${RESET_TERM}"
 	@echo
 
-client_start: check_client_link check_client_pid
+client_start: check_client_link client_check_pid
 	@echo
+	@echo "About to start \"${CLIENT_EXE_NAME}\" using host \"${HOST}\", port \"${PORT}\", and file \"${SAMPLE}\"..."
 	@echo "Starting ${CLIENT_EXE_NAME} using host ${HOST}, port ${PORT}, and file ${SAMPLE}" > ${CLIENT_LOG}
 	@echo "Executed on "`date` >> ${CLIENT_LOG}
 	@${SDK_LOAD_PATH} ./${CLIENT_EXE_NAME} ${HOST} ${PORT} ${SAMPLE} >> ${CLIENT_LOG} 2>&1 &
@@ -68,11 +73,11 @@ client_start: check_client_link check_client_pid
 stop: client_stop server_stop proxy_stop status
 	@echo "Completed program stop for client, server, and proxy."
 
-proxy_stop: check_proxy_pid
+proxy_stop: proxy_check_pid
 
-server_stop: check_server_pid
+server_stop: server_check_pid
 
-client_stop: check_client_pid
+client_stop: client_check_pid
 
 check_links: check_server_link check_client_link
 	@echo "Completed check_links"
@@ -93,9 +98,9 @@ check_client_link:
 		exit 1;\
 	fi
 
-check_pids: check_proxy_pid check_server_pid check_client_pid
+check_pids: proxy_check_pid server_check_pid client_check_pid
 
-check_proxy_pid: 
+proxy_check_pid: 
 	@if [ -f ${PROXY_PID_FILE} ] && [ -s ${PROXY_PID_FILE} ]; then\
 		if [ "`cat ${PROXY_PID_FILE} | wc -l`" -ne "1" ]; then\
 			echo;\
@@ -112,52 +117,83 @@ check_proxy_pid:
 			exit 1;\
 		fi;\
 		echo;\
-		echo "${BOLD_RED}Found a pre-existing proxy pid file \"${PROXY_PID_FILE}\" with pid ${PROXY_PID}${RESET_TERM}";\
-		ps -f --pid ${PROXY_PID} ;\
+		echo "${BOLD_RED}Found a pre-existing proxy pid file \"${PROXY_PID_FILE}\" with pid ${PROXY_PID}.${RESET_TERM}";\
+		ps -f --pid "${PROXY_PID}";\
 		echo;\
-		read -p "Would you like to kill the process before proceeding (yes/skip/abort)?" ANSWER;\
+		read -p "Would you like to kill the process before proceeding (yes/abort)?" ANSWER;\
 		echo;\
-		if [ "$${ANSWER}" = "yes" ]; then\
-			echo "${BOLD_RED}Aborting process ${PROXY_PID}, and removing file \"${PROXY_PID_FILE}\".${RESET_TERM}";\
-			kill ${PROXY_PID};\
-			rm -f ${PROXY_PID_FILE};\
-			echo "Process and/or pid file eliminated.";\
+		if [ "$${ANSWER}" = "abort" ]; then\
 			echo;\
-			exit 1;\
-		fi;\
-		if [ "$${ANSWER}" != "skip" ]; then\
 			echo "${BOLD_RED}Terminating make at user request.${RESET_TERM}";\
 			echo;\
 			exit 1;\
 		fi;\
-		echo;\
-		echo "${BOLD_GREEN}process ${PROXY_PID} running, pidfile \"${PROXY_PID_FILE}\".${RESET_TERM}";\
-		if [ 1 -lt "`ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}" | wc -l`" ]; then\
+		if [ "$${ANSWER}" = "yes" ]; then\
+			echo "${BOLD_RED}Terminating process ${PROXY_PID}, and removing file \"${PROXY_PID_FILE}\".${RESET_TERM}";\
+			kill ${PROXY_PID};\
+			rm -f ${PROXY_PID_FILE};\
+			sleep 1;\
+			echo "Process and/or pid file eliminated.";\
 			echo;\
-			echo "${BOLD_RED}ERROR: Found one or more matching proxy processes with no corresponding \"${PROXY_PID_FILE}\".${RESET_TERM}";\
-			ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}";\
-			echo;\
-			while [ -n "`ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}"`" ]; do\
-				echo;\
-				read -p "Would you like to kill process `ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}" | awk ' { print $$2 } '` (yes/no/abort)?" ANSWER;\
-				if [ "$${ANSWER}" = "yes" ]; then\
-					echo;\
-					echo "${BOLD_RED}Terminating process at user request.${RESET_TERM}";\
-					kill -9 `ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}" | awk ' { print $$2 } '`;\
-					echo;\
-				fi;\
-				if [ "$${ANSWER}" = "abort" ]; then\
-					echo;\
-					echo "${BOLD_RED}Aborting make at user request.${RESET_TERM}";\
-					echo;\
-					exit 1;\
-				fi;\
-			done;\
 		fi;\
-		echo "Completed check_proxy_pid";\
+	elif [ 0 -lt "`ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}" | wc -l`" ]; then\
+		echo;\
+		echo "${BOLD_RED}ERROR: Found one or more matching proxy processes with no corresponding pid file(\"${PROXY_PID_FILE}\").${RESET_TERM}";\
+		echo;\
+		ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}";\
+		while [ -n "`ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}"`" ]; do\
+			echo;\
+			read -p "Would you like to kill process `ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}" | awk ' { print $$2 } '` (yes/abort)?" ANSWER;\
+			if [ "$${ANSWER}" = "abort" ]; then\
+				echo;\
+				echo "${BOLD_RED}Aborting make at user request.${RESET_TERM}";\
+				echo;\
+				exit 1;\
+			fi;\
+			if [ "$${ANSWER}" = "yes" ]; then\
+				echo;\
+				echo "${BOLD_RED}Terminating process at user request.${RESET_TERM}";\
+				kill -9 `ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}" | awk ' { print $$2 } '`;\
+				sleep 1;\
+				echo;\
+			fi;\
+		done;\
 	fi;
+	@if [ 2 -le "`ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}" | wc -l`" ]; then\
+		echo;\
+		echo "${BOLD_RED}WARNING: Multiple proxies are running!${RESET_TERM}";\
+		ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}";\
+		echo;\
+		echo "${BOLD_RED}Run \"make proxy_stop\" and terminate superflous proxies before continuing.${RESET_TERM}";\
+		echo;\
+	fi;
+	@echo "Completed proxy_check_pid";
 
-check_server_pid: 
+junky:
+#	if [ 0 -lt "`ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}" | wc -l`" ]; then\
+#			echo;\
+#			echo "${BOLD_RED}ERROR: Found one or more matching proxy processes with no corresponding pid file(\"${PROXY_PID_FILE}\").${RESET_TERM}";\
+#			ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}";\
+#			while [ -n "`ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}"`" ]; do\
+#				echo;\
+#				read -p "Would you like to kill process `ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}" | awk ' { print $$2 } '` (yes/abort)?" ANSWER;\
+#				if [ "$${ANSWER}" = "abort" ]; then\
+#					echo;\
+#					echo "${BOLD_RED}Aborting make at user request.${RESET_TERM}";\
+#					echo;\
+#					exit 1;\
+#				fi;\
+#				if [ "$${ANSWER}" = "yes" ]; then\
+#					echo;\
+#					echo "${BOLD_RED}Terminating process at user request.${RESET_TERM}";\
+#					kill -9 `ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}" | awk ' { print $$2 } '`;\
+#					echo;\
+#				fi;\
+#			done;\
+#		fi;\
+#		echo;\
+
+server_check_pid: 
 	@if [ -f ${SERVER_PID_FILE} ] && [ -s ${SERVER_PID_FILE} ]; then\
 		if [ "`cat ${SERVER_PID_FILE} | wc -l`" -ne "1" ]; then\
 		echo;\
@@ -212,10 +248,10 @@ check_server_pid:
 			fi;\
 		done;\
 		echo;\
-		echo "Completed check_server_pid";\
+		echo "Completed server_check_pid";\
 	fi;
 
-check_client_pid:
+client_check_pid:
 	@if [ -f "${CLIENT_PID_FILE}" ] && [ -s "${CLIENT_PID_FILE}" ]; then\
 		if [ "`cat "${CLIENT_PID_FILE}" | wc -l`" -ne "1" ]; then\
 		echo;\
@@ -270,7 +306,7 @@ check_client_pid:
 			fi;\
 		done;\
 		echo;\
-		echo "Completed check_client_pid";\
+		echo "Completed client_check_pid";\
 	fi;
 
 status: title_status proxy_status server_status client_status 
@@ -284,10 +320,13 @@ title_status:
 		ps -ef | head -1;\
 	fi;
 
-proxy_status:
+proxy_status: proxy_check_pid
 	@if [ -n "`ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}"`" ]; then\
 		if [ -n "`ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}"`" ]; then\
+			echo;\
+			echo "${BOLD_GREEN}Found Proxy process running.${RESET_TERM}";\
 			ps -ef | grep -v grep | grep proxy | grep "${PROXY_TYPE}";\
+			echo;\
 		fi;\
 	else\
 		echo;\
@@ -298,7 +337,10 @@ proxy_status:
 server_status:
 	@if [ -n "`ps -ef | grep -v grep | grep "${SERVER_EXE_NAME}" | grep "${HOST}" | grep "${PORT}"`" ]; then\
 		if [ -n "`ps -ef | grep -v grep | grep "${SERVER_EXE_NAME}" | grep "${HOST}" | grep "${PORT}"`" ]; then\
+			echo;\
+			echo "${BOLD_GREEN}Found Server process running.${RESET_TERM}";\
 			ps -ef | grep -v grep | grep "${SERVER_EXE_NAME}" | grep "${HOST}" | grep "${PORT}";\
+			echo;\
 		fi;\
 	else\
 		echo;\
@@ -309,7 +351,10 @@ server_status:
 client_status:
 	@if [ -n "`ps -ef | grep -v grep | grep "${CLIENT_EXE_NAME}" | grep "${HOST}" | grep "${PORT}"`" ]; then\
 		if [ -n "`ps -ef | grep -v grep | grep "${CLIENT_EXE_NAME}" | grep "${HOST}" | grep "${PORT}"`" ]; then\
+			echo;\
+			echo "${BOLD_GREEN}Found Client process running.${RESET_TERM}";\
 			ps -ef | grep -v grep | grep "${CLIENT_EXE_NAME}" | grep "${HOST}" | grep "${PORT}";\
+			echo;\
 		fi;\
 	else\
 		echo;\
